// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250124204939_PhotoUploadingAdded")]
    partial class PhotoUploadingAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("API.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            AnswerText = "Gode kollega",
                            QuestionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            AnswerId = 2,
                            AnswerText = "matematikk :) ",
                            QuestionId = 3,
                            UserId = 3
                        },
                        new
                        {
                            AnswerId = 3,
                            AnswerText = "for lite ferie :) ",
                            QuestionId = 2,
                            UserId = 4
                        },
                        new
                        {
                            AnswerId = 4,
                            AnswerText = "for mye teori :) ",
                            QuestionId = 4,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("API.Models.AppRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Mentor"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("API.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Description = "I'm admin",
                            FirstName = "Admin",
                            Gender = "Female",
                            LastName = "Admin",
                            PasswordHash = new byte[] { 65, 81, 65, 65, 65, 65, 73, 65, 65, 89, 97, 103, 65, 65, 65, 65, 69, 66, 115, 84, 111, 113, 54, 74, 84, 116, 115, 43, 89, 87, 120, 121, 53, 57, 80, 65, 87, 80, 83, 112, 101, 89, 49, 74, 101, 101, 99, 116, 98, 43, 77, 68, 47, 43, 114, 118, 117, 119, 98, 51, 82, 119, 47, 70, 108, 75, 66, 48, 112, 67, 112, 89, 115, 81, 117, 83, 55, 68, 117, 71, 97, 81, 61, 61 },
                            PasswordSalt = new byte[0],
                            PhotoUrl = "",
                            PublicId = "",
                            UserName = "Admin@gmail.com"
                        },
                        new
                        {
                            UserId = 2,
                            Description = "mentor description...",
                            FirstName = "Mentor1",
                            Gender = "Male",
                            LastName = "ment1",
                            PasswordHash = new byte[] { 65, 81, 65, 65, 65, 65, 73, 65, 65, 89, 97, 103, 65, 65, 65, 65, 69, 74, 102, 69, 80, 52, 55, 108, 65, 70, 52, 85, 112, 119, 121, 117, 57, 67, 89, 121, 56, 120, 118, 56, 108, 112, 48, 53, 48, 72, 84, 47, 100, 71, 81, 109, 53, 107, 43, 65, 66, 48, 84, 85, 114, 110, 65, 120, 107, 97, 102, 104, 57, 78, 90, 84, 71, 52, 48, 116, 54, 52, 118, 99, 102, 119, 61, 61 },
                            PasswordSalt = new byte[0],
                            PhotoUrl = "https://picsum.photos/200",
                            PublicId = "",
                            UserName = "mentor1@gmail.com"
                        },
                        new
                        {
                            UserId = 3,
                            Description = "stud description,",
                            FirstName = "Student1",
                            Gender = "Male",
                            LastName = "stud1VGS",
                            PasswordHash = new byte[] { 65, 81, 65, 65, 65, 65, 73, 65, 65, 89, 97, 103, 65, 65, 65, 65, 69, 76, 105, 118, 65, 113, 71, 49, 117, 113, 109, 109, 99, 51, 118, 111, 55, 121, 73, 48, 120, 87, 86, 68, 113, 105, 85, 43, 84, 48, 66, 78, 98, 68, 85, 82, 120, 77, 54, 90, 50, 115, 83, 72, 87, 106, 78, 78, 73, 90, 53, 72, 98, 84, 79, 104, 79, 49, 53, 57, 120, 68, 80, 106, 70, 103, 61, 61 },
                            PasswordSalt = new byte[0],
                            PhotoUrl = "https://picsum.photos/200",
                            PublicId = "",
                            UserName = "student1@gmail.com"
                        },
                        new
                        {
                            UserId = 4,
                            Description = "mentor description...",
                            FirstName = "Mentor2",
                            Gender = "Female",
                            LastName = "ment2",
                            PasswordHash = new byte[] { 65, 81, 65, 65, 65, 65, 73, 65, 65, 89, 97, 103, 65, 65, 65, 65, 69, 68, 116, 110, 98, 112, 69, 56, 108, 89, 107, 54, 108, 71, 103, 117, 77, 43, 121, 55, 87, 54, 119, 117, 101, 51, 68, 52, 88, 79, 121, 65, 43, 83, 50, 110, 104, 87, 103, 75, 120, 97, 76, 112, 47, 75, 104, 106, 99, 102, 114, 72, 79, 100, 47, 68, 53, 118, 107, 74, 87, 56, 97, 54, 116, 81, 61, 61 },
                            PasswordSalt = new byte[0],
                            PhotoUrl = "https://picsum.photos/200",
                            PublicId = "",
                            UserName = "mentor2@gmail.com"
                        },
                        new
                        {
                            UserId = 5,
                            Description = "stud description",
                            FirstName = "Student2",
                            Gender = "Male",
                            LastName = "studVGS2",
                            PasswordHash = new byte[] { 65, 81, 65, 65, 65, 65, 73, 65, 65, 89, 97, 103, 65, 65, 65, 65, 69, 78, 49, 78, 85, 100, 121, 98, 76, 107, 54, 122, 71, 99, 75, 108, 122, 52, 57, 54, 104, 71, 88, 90, 66, 100, 90, 77, 121, 115, 84, 82, 70, 84, 47, 77, 52, 110, 90, 100, 73, 81, 84, 84, 51, 85, 50, 53, 43, 117, 116, 114, 47, 65, 66, 107, 76, 110, 108, 65, 89, 66, 71, 99, 72, 81, 61, 61 },
                            PasswordSalt = new byte[0],
                            PhotoUrl = "https://picsum.photos/200",
                            PublicId = "",
                            UserName = "student2@gmail.com"
                        });
                });

            modelBuilder.Entity("API.Models.Degree", b =>
                {
                    b.Property<int>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DegreeId");

                    b.ToTable("Degrees");

                    b.HasData(
                        new
                        {
                            DegreeId = 1,
                            DegreeName = "VGS"
                        },
                        new
                        {
                            DegreeId = 2,
                            DegreeName = "Bachelor degree"
                        },
                        new
                        {
                            DegreeId = 3,
                            DegreeName = "Masters degree"
                        },
                        new
                        {
                            DegreeId = 4,
                            DegreeName = "Phd"
                        });
                });

            modelBuilder.Entity("API.Models.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DegreeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EducationId");

                    b.HasIndex("DegreeId");

                    b.HasIndex("UserId");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            EducationId = 1,
                            DegreeId = 1,
                            EndDate = new DateTime(2025, 1, 24, 21, 49, 37, 750, DateTimeKind.Local).AddTicks(7965),
                            SchoolName = "school-name",
                            StartDate = new DateTime(2025, 1, 24, 21, 49, 37, 745, DateTimeKind.Local).AddTicks(2750),
                            StudyCity = "Oslo",
                            UserId = 2
                        },
                        new
                        {
                            EducationId = 2,
                            DegreeId = 2,
                            EndDate = new DateTime(2025, 1, 24, 21, 49, 37, 750, DateTimeKind.Local).AddTicks(9695),
                            SchoolName = "school-name",
                            StartDate = new DateTime(2025, 1, 24, 21, 49, 37, 750, DateTimeKind.Local).AddTicks(9679),
                            StudyCity = "Bergen",
                            UserId = 3
                        },
                        new
                        {
                            EducationId = 3,
                            DegreeId = 3,
                            EndDate = new DateTime(2025, 1, 24, 21, 49, 37, 750, DateTimeKind.Local).AddTicks(9705),
                            SchoolName = "school-name",
                            StartDate = new DateTime(2025, 1, 24, 21, 49, 37, 750, DateTimeKind.Local).AddTicks(9703),
                            StudyCity = "Stavanger",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("API.Models.FieldOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FieldOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Health"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Politics"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Social science"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Hospitality"
                        });
                });

            modelBuilder.Entity("API.Models.Industry", b =>
                {
                    b.Property<int>("IndustryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IndustryId");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            IndustryId = 1,
                            IndustryName = "Barn, skole og undervisning"
                        },
                        new
                        {
                            IndustryId = 2,
                            IndustryName = "Bygg og anlegg"
                        },
                        new
                        {
                            IndustryId = 4,
                            IndustryName = "Helse og omsorg"
                        },
                        new
                        {
                            IndustryId = 5,
                            IndustryName = "Industri og produksjon"
                        },
                        new
                        {
                            IndustryId = 6,
                            IndustryName = "Konsulent og rådgiving"
                        },
                        new
                        {
                            IndustryId = 7,
                            IndustryName = "IT"
                        },
                        new
                        {
                            IndustryId = 8,
                            IndustryName = "Kraft og energi"
                        },
                        new
                        {
                            IndustryId = 9,
                            IndustryName = "Maritim og offshoe"
                        },
                        new
                        {
                            IndustryId = 10,
                            IndustryName = "Offentelig administrasjon"
                        },
                        new
                        {
                            IndustryId = 11,
                            IndustryName = "Transport og logistikk"
                        });
                });

            modelBuilder.Entity("API.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldOfInterestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InterestId");

                    b.HasIndex("FieldOfInterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            FieldOfInterestId = 1,
                            InterestName = "IT"
                        },
                        new
                        {
                            InterestId = 2,
                            FieldOfInterestId = 2,
                            InterestName = "Nurse"
                        },
                        new
                        {
                            InterestId = 3,
                            FieldOfInterestId = 3,
                            InterestName = "Public policy"
                        },
                        new
                        {
                            InterestId = 4,
                            FieldOfInterestId = 4,
                            InterestName = "Social work"
                        },
                        new
                        {
                            InterestId = 5,
                            FieldOfInterestId = 5,
                            InterestName = "Hotel managment"
                        });
                });

            modelBuilder.Entity("API.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            QuestionText = "Hva er den beste med jobben din?"
                        },
                        new
                        {
                            QuestionId = 2,
                            QuestionText = "Hva er den verste med jobben din, og Hvorfor?"
                        },
                        new
                        {
                            QuestionId = 3,
                            QuestionText = "Hvilket fag er du mest glad i?"
                        },
                        new
                        {
                            QuestionId = 4,
                            QuestionText = "Hvilket fag er du mest IKKE glad i, og Hvorfor?"
                        });
                });

            modelBuilder.Entity("API.Models.UserInterest", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterests");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            InterestId = 1
                        },
                        new
                        {
                            UserId = 3,
                            InterestId = 2
                        },
                        new
                        {
                            UserId = 4,
                            InterestId = 3
                        },
                        new
                        {
                            UserId = 5,
                            InterestId = 4
                        });
                });

            modelBuilder.Entity("API.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("API.Models.WorkExperience", b =>
                {
                    b.Property<int>("WorkExpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IndustryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jobtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkExpId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkExperiences");

                    b.HasData(
                        new
                        {
                            WorkExpId = 1,
                            CompanyName = "Avonova Norge",
                            IndustryId = 1,
                            Jobtitle = "job-title",
                            UserId = 3
                        },
                        new
                        {
                            WorkExpId = 2,
                            CompanyName = "Innovation Norge",
                            IndustryId = 2,
                            Jobtitle = "job-title",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("API.Models.Answer", b =>
                {
                    b.HasOne("API.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.AppUser", "AppUser")
                        .WithMany("Answers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("API.Models.Education", b =>
                {
                    b.HasOne("API.Models.Degree", "Degree")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.AppUser", "AppUser")
                        .WithMany("Educations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("API.Models.Interest", b =>
                {
                    b.HasOne("API.Models.FieldOfInterest", "FieldOfInterest")
                        .WithMany("Interests")
                        .HasForeignKey("FieldOfInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldOfInterest");
                });

            modelBuilder.Entity("API.Models.UserInterest", b =>
                {
                    b.HasOne("API.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.AppUser", "AppUser")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Interest");
                });

            modelBuilder.Entity("API.Models.UserRole", b =>
                {
                    b.HasOne("API.Models.AppRole", "AppRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.AppUser", "AppUser")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Models.WorkExperience", b =>
                {
                    b.HasOne("API.Models.Industry", "Indudtry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.AppUser", "AppUser")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Indudtry");
                });

            modelBuilder.Entity("API.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("API.Models.AppUser", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Educations");

                    b.Navigation("Roles");

                    b.Navigation("UserInterests");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("API.Models.FieldOfInterest", b =>
                {
                    b.Navigation("Interests");
                });

            modelBuilder.Entity("API.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
