// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            AnswerText = "Gode kollega",
                            QuestionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            AnswerId = 2,
                            AnswerText = "matematikk :) ",
                            QuestionId = 3,
                            UserId = 3
                        },
                        new
                        {
                            AnswerId = 3,
                            AnswerText = "for lite ferie :) ",
                            QuestionId = 2,
                            UserId = 4
                        },
                        new
                        {
                            AnswerId = 4,
                            AnswerText = "for mye teori :) ",
                            QuestionId = 4,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("API.Models.AppRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Mentor"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("API.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Description = "I'm admin",
                            FirstName = "Admin",
                            Gender = "Female",
                            LastName = "Admin",
                            PasswordHash = new byte[] { 65, 81, 65, 65, 65, 65, 73, 65, 65, 89, 97, 103, 65, 65, 65, 65, 69, 80, 108, 89, 55, 113, 49, 116, 84, 48, 81, 114, 103, 54, 67, 107, 103, 72, 49, 82, 82, 50, 118, 86, 75, 99, 66, 116, 86, 82, 48, 71, 89, 56, 70, 85, 76, 111, 122, 70, 87, 113, 71, 49, 105, 122, 121, 51, 56, 119, 77, 90, 43, 100, 57, 102, 69, 80, 67, 54, 70, 98, 57, 88, 87, 103, 61, 61 },
                            PasswordSalt = new byte[0],
                            PhotoUrl = "",
                            PublicId = "",
                            UserName = "Admin@gmail.com"
                        },
                        new
                        {
                            UserId = 2,
                            Description = "mentor description...",
                            FirstName = "Mentor1",
                            Gender = "Male",
                            LastName = "ment1",
                            PasswordHash = new byte[] { 65, 81, 65, 65, 65, 65, 73, 65, 65, 89, 97, 103, 65, 65, 65, 65, 69, 66, 53, 109, 119, 55, 57, 50, 110, 121, 48, 74, 119, 52, 109, 84, 66, 56, 99, 77, 104, 71, 68, 55, 87, 109, 105, 50, 98, 74, 115, 112, 43, 78, 52, 55, 112, 104, 89, 105, 102, 82, 80, 88, 55, 102, 66, 53, 86, 122, 81, 74, 66, 90, 111, 82, 120, 66, 113, 67, 79, 68, 111, 73, 78, 103, 61, 61 },
                            PasswordSalt = new byte[0],
                            PhotoUrl = "https://picsum.photos/200",
                            PublicId = "",
                            UserName = "mentor1@gmail.com"
                        },
                        new
                        {
                            UserId = 3,
                            Description = "stud description,",
                            FirstName = "Student1",
                            Gender = "Male",
                            LastName = "stud1VGS",
                            PasswordHash = new byte[] { 65, 81, 65, 65, 65, 65, 73, 65, 65, 89, 97, 103, 65, 65, 65, 65, 69, 71, 87, 67, 51, 49, 48, 76, 74, 102, 122, 56, 100, 101, 74, 74, 115, 72, 52, 66, 56, 73, 47, 86, 52, 52, 83, 107, 99, 87, 70, 65, 49, 102, 75, 120, 104, 120, 74, 73, 77, 71, 80, 108, 85, 108, 80, 56, 77, 51, 98, 79, 71, 90, 51, 66, 100, 103, 86, 57, 99, 104, 77, 88, 122, 103, 61, 61 },
                            PasswordSalt = new byte[0],
                            PhotoUrl = "https://picsum.photos/200",
                            PublicId = "",
                            UserName = "student1@gmail.com"
                        },
                        new
                        {
                            UserId = 4,
                            Description = "mentor description...",
                            FirstName = "Mentor2",
                            Gender = "Female",
                            LastName = "ment2",
                            PasswordHash = new byte[] { 65, 81, 65, 65, 65, 65, 73, 65, 65, 89, 97, 103, 65, 65, 65, 65, 69, 77, 116, 50, 50, 86, 106, 100, 52, 113, 119, 57, 97, 48, 71, 114, 98, 83, 88, 114, 90, 83, 80, 89, 122, 105, 117, 100, 79, 111, 84, 88, 50, 50, 56, 116, 52, 78, 57, 119, 119, 82, 118, 114, 65, 69, 73, 100, 84, 106, 78, 116, 49, 106, 90, 97, 73, 55, 116, 118, 54, 53, 116, 66, 101, 81, 61, 61 },
                            PasswordSalt = new byte[0],
                            PhotoUrl = "https://picsum.photos/200",
                            PublicId = "",
                            UserName = "mentor2@gmail.com"
                        },
                        new
                        {
                            UserId = 5,
                            Description = "stud description",
                            FirstName = "Student2",
                            Gender = "Male",
                            LastName = "studVGS2",
                            PasswordHash = new byte[] { 65, 81, 65, 65, 65, 65, 73, 65, 65, 89, 97, 103, 65, 65, 65, 65, 69, 78, 80, 86, 118, 70, 90, 117, 72, 104, 118, 47, 56, 50, 88, 76, 122, 118, 108, 48, 97, 117, 82, 43, 53, 108, 104, 68, 77, 83, 53, 101, 65, 121, 101, 122, 78, 76, 102, 80, 53, 111, 107, 108, 82, 49, 68, 101, 100, 119, 119, 75, 107, 88, 99, 111, 86, 72, 76, 73, 100, 111, 81, 43, 67, 119, 61, 61 },
                            PasswordSalt = new byte[0],
                            PhotoUrl = "https://picsum.photos/200",
                            PublicId = "",
                            UserName = "student2@gmail.com"
                        });
                });

            modelBuilder.Entity("API.Models.Degree", b =>
                {
                    b.Property<int>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegreeId"));

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DegreeId");

                    b.ToTable("Degrees");

                    b.HasData(
                        new
                        {
                            DegreeId = 1,
                            DegreeName = "VGS"
                        },
                        new
                        {
                            DegreeId = 2,
                            DegreeName = "Bachelor degree"
                        },
                        new
                        {
                            DegreeId = 3,
                            DegreeName = "Masters degree"
                        },
                        new
                        {
                            DegreeId = 4,
                            DegreeName = "Phd"
                        });
                });

            modelBuilder.Entity("API.Models.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"));

                    b.Property<int>("DegreeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudyCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EducationId");

                    b.HasIndex("DegreeId");

                    b.HasIndex("UserId");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            EducationId = 1,
                            DegreeId = 1,
                            EndDate = new DateTime(2025, 2, 3, 11, 5, 54, 945, DateTimeKind.Local).AddTicks(4490),
                            SchoolName = "school-name",
                            StartDate = new DateTime(2025, 2, 3, 11, 5, 54, 939, DateTimeKind.Local).AddTicks(8106),
                            StudyCity = "Oslo",
                            UserId = 2
                        },
                        new
                        {
                            EducationId = 2,
                            DegreeId = 2,
                            EndDate = new DateTime(2025, 2, 3, 11, 5, 54, 945, DateTimeKind.Local).AddTicks(6216),
                            SchoolName = "school-name",
                            StartDate = new DateTime(2025, 2, 3, 11, 5, 54, 945, DateTimeKind.Local).AddTicks(6199),
                            StudyCity = "Bergen",
                            UserId = 3
                        },
                        new
                        {
                            EducationId = 3,
                            DegreeId = 3,
                            EndDate = new DateTime(2025, 2, 3, 11, 5, 54, 945, DateTimeKind.Local).AddTicks(6224),
                            SchoolName = "school-name",
                            StartDate = new DateTime(2025, 2, 3, 11, 5, 54, 945, DateTimeKind.Local).AddTicks(6222),
                            StudyCity = "Stavanger",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("API.Models.FieldOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FieldOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Health"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Politics"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Social science"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Hospitality"
                        });
                });

            modelBuilder.Entity("API.Models.Industry", b =>
                {
                    b.Property<int>("IndustryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndustryId"));

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IndustryId");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            IndustryId = 1,
                            IndustryName = "Barn, skole og undervisning"
                        },
                        new
                        {
                            IndustryId = 2,
                            IndustryName = "Bygg og anlegg"
                        },
                        new
                        {
                            IndustryId = 4,
                            IndustryName = "Helse og omsorg"
                        },
                        new
                        {
                            IndustryId = 5,
                            IndustryName = "Industri og produksjon"
                        },
                        new
                        {
                            IndustryId = 6,
                            IndustryName = "Konsulent og rådgiving"
                        },
                        new
                        {
                            IndustryId = 7,
                            IndustryName = "IT"
                        },
                        new
                        {
                            IndustryId = 8,
                            IndustryName = "Kraft og energi"
                        },
                        new
                        {
                            IndustryId = 9,
                            IndustryName = "Maritim og offshoe"
                        },
                        new
                        {
                            IndustryId = 10,
                            IndustryName = "Offentelig administrasjon"
                        },
                        new
                        {
                            IndustryId = 11,
                            IndustryName = "Transport og logistikk"
                        });
                });

            modelBuilder.Entity("API.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<int>("FieldOfInterestId")
                        .HasColumnType("int");

                    b.Property<string>("InterestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.HasIndex("FieldOfInterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            FieldOfInterestId = 1,
                            InterestName = "IT"
                        },
                        new
                        {
                            InterestId = 2,
                            FieldOfInterestId = 2,
                            InterestName = "Nurse"
                        },
                        new
                        {
                            InterestId = 3,
                            FieldOfInterestId = 3,
                            InterestName = "Public policy"
                        },
                        new
                        {
                            InterestId = 4,
                            FieldOfInterestId = 4,
                            InterestName = "Social work"
                        },
                        new
                        {
                            InterestId = 5,
                            FieldOfInterestId = 5,
                            InterestName = "Hotel managment"
                        });
                });

            modelBuilder.Entity("API.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            QuestionText = "Hva er den beste med jobben din?"
                        },
                        new
                        {
                            QuestionId = 2,
                            QuestionText = "Hva er den verste med jobben din, og Hvorfor?"
                        },
                        new
                        {
                            QuestionId = 3,
                            QuestionText = "Hvilket fag er du mest glad i?"
                        },
                        new
                        {
                            QuestionId = 4,
                            QuestionText = "Hvilket fag er du mest IKKE glad i, og Hvorfor?"
                        });
                });

            modelBuilder.Entity("API.Models.UserInterest", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterests");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            InterestId = 1
                        },
                        new
                        {
                            UserId = 3,
                            InterestId = 2
                        },
                        new
                        {
                            UserId = 4,
                            InterestId = 3
                        },
                        new
                        {
                            UserId = 5,
                            InterestId = 4
                        });
                });

            modelBuilder.Entity("API.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("API.Models.WorkExperience", b =>
                {
                    b.Property<int>("WorkExpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkExpId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("Jobtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WorkExpId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkExperiences");

                    b.HasData(
                        new
                        {
                            WorkExpId = 1,
                            CompanyName = "Avonova Norge",
                            IndustryId = 1,
                            Jobtitle = "job-title",
                            UserId = 3
                        },
                        new
                        {
                            WorkExpId = 2,
                            CompanyName = "Innovation Norge",
                            IndustryId = 2,
                            Jobtitle = "job-title",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("API.Models.Answer", b =>
                {
                    b.HasOne("API.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.AppUser", "AppUser")
                        .WithMany("Answers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("API.Models.Education", b =>
                {
                    b.HasOne("API.Models.Degree", "Degree")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.AppUser", "AppUser")
                        .WithMany("Educations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("API.Models.Interest", b =>
                {
                    b.HasOne("API.Models.FieldOfInterest", "FieldOfInterest")
                        .WithMany("Interests")
                        .HasForeignKey("FieldOfInterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldOfInterest");
                });

            modelBuilder.Entity("API.Models.UserInterest", b =>
                {
                    b.HasOne("API.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.AppUser", "AppUser")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Interest");
                });

            modelBuilder.Entity("API.Models.UserRole", b =>
                {
                    b.HasOne("API.Models.AppRole", "AppRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.AppUser", "AppUser")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Models.WorkExperience", b =>
                {
                    b.HasOne("API.Models.Industry", "Indudtry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.AppUser", "AppUser")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Indudtry");
                });

            modelBuilder.Entity("API.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("API.Models.AppUser", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Educations");

                    b.Navigation("Roles");

                    b.Navigation("UserInterests");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("API.Models.FieldOfInterest", b =>
                {
                    b.Navigation("Interests");
                });

            modelBuilder.Entity("API.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
